AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Provision the AWS Lambda function of s3-monitor
Parameters:
  ENV:
    Type: String
    Default: dev
    Description: Environment name
  PROJECT:
    Type: String
    Default: no_name_project
    Description: Project name
  AWSREGION:
    Type: String
    Default: eu-west-1
    Description: AWS Region
  MONITORINGBUCKET:
    Type: String
    Default: no_bucket_vars_definied
    Description: Monitored bucket name
  S3PREFIX:
    Type: String
    Default: no_prefix_defined
    Description: S3 prefix to monitor
  RECIPIENTS:
    Type: String
    Default: no_recipients_defined@domain.com
    Description: Recipients emails addresses
  SENDER:
    Type: String
    Default: no_sender_defined@domain.com
    Description: Sender email addresses
Resources:
  s3monitor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: s3-monitor-${ENV}
      Description:
        Fn::Sub: S3 Backup Monitor (${PROJECT})
      Handler: handlers.main
      Runtime: python3.8
      CodeUri: s3://zoph-s3monitor-artifacts/e67112ef025d467e1fc91735f3108cd2
      MemorySize: 128
      Timeout: 30
      Layers:
      - Ref: boto3layer
      Environment:
        Variables:
          MONITORINGBUCKET:
            Ref: MONITORINGBUCKET
          S3PREFIX:
            Ref: S3PREFIX
          RECIPIENTS:
            Ref: RECIPIENTS
          SENDER:
            Ref: SENDER
          AWSREGION:
            Ref: AWSREGION
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:List*
          Resource:
            Fn::Sub: arn:aws:s3:::${MONITORINGBUCKET}
        - Effect: Allow
          Action:
          - ses:SendEmail
          Resource: '*'
      Events:
        Timer:
          Type: Schedule
          Properties:
            Name: s3-monitor-schedule
            Schedule: cron(0 4 * * ? *)
      Tags:
        Project:
          Ref: PROJECT
        Environment:
          Ref: ENV
        Monitoring_Bucket_Name:
          Ref: MONITORINGBUCKET
        Region:
          Ref: AWSREGION
  boto3layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: boto3-layer
      Description: boto3 and botocore layer
      ContentUri: s3://zoph-s3monitor-artifacts/87423961ed9f2c60e77296aea8a01f15
      CompatibleRuntimes:
      - python2.7
      - python3.6
      - python3.7
      - python3.8
      LicenseInfo: Available under the MIT-0 license.
      RetentionPolicy: Retain
