AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Provision the AWS Lambda function of s3-monitor

Parameters:

  env:
    Type: String
    Default: prod
    Description: Environment Name

  LambdaRole:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: s3-monitor-role-prod
    Description: Get from Parameter Store the ARN of the LambdaRole

Resources:
  s3monitor:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub s3-monitor-${env}
      Description: Monitoring for S3 (Backups Jeedom)
      Handler: s3monitor.main
      Runtime: python3.6
      CodeUri: ./build
      Role: !Sub ${LambdaRole}
      MemorySize: 128
      Timeout: 30
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
      Tags:
        Project: s3-monitor