AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Provision the AWS Lambda function of s3-monitor

Parameters:

  env:
    Type: String
    Default: dev
    Description: Environment Name

Resources:
  s3monitor:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub s3-monitor-${env}
      Description: Monitoring for S3 (Backups Jeedom)
      Handler: handlers.main
      Runtime: python3.7
      CodeUri: ./build
      MemorySize: 128
      Timeout: 30
      Layers:
        - !Ref boto3layer
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
              - s3:List*
              Resource: 'arn:aws:s3:::zoph.backup'
            - Effect: Allow
              Action:
                - ses:SendEmail
              Resource: '*'
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
      Tags:
        Project: s3-monitor

  boto3layer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: boto3-layer
      Description: boto3 and botocore layer
      ContentUri: ./layer
      CompatibleRuntimes:
        - python2.7
        - python3.6
        - python3.7
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain
