AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Provision the AWS Lambda function of s3-monitor
###########################################################
Parameters:
###########################################################
  ENV:
    Type: String
    Default: dev
    Description: Environment Name
  PROJECT:
    Type: String
    Default: noname_project
    Description: Project Name
  MONITORINGBUCKET:
    Type: String
    Default: no_bucket_vars_definied
    Description: Monitored Bucket Name
  S3PREFIX:
    Type: String
    Default: no_prefix_defined
    Description: S3 Prefix to monitor
###########################################################
Resources:
###########################################################
  s3monitor:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub s3-monitor-${ENV}
      Description: !Sub File monitoring for S3 (${PROJECT})
      Handler: handlers.main
      Runtime: python3.7
      CodeUri: ./build
      MemorySize: 128
      Timeout: 30
      Layers:
        - !Ref boto3layer
      Environment:
        Variables:
          MONITORINGBUCKET: !Ref MONITORINGBUCKET
          S3PREFIX: !Ref S3PREFIX
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
              - s3:List*
              Resource: !Sub 'arn:aws:s3:::${MONITORINGBUCKET}'
            - Effect: Allow
              Action:
                - ses:SendEmail
              Resource: '*'
      Events:
        Timer:
          Type: Schedule
          Properties:
            Name: s3-monitor-schedule
            Schedule: cron(0 4 * * ? *)
      Tags:
        Project: !Ref PROJECT

  boto3layer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: boto3-layer
      Description: boto3 and botocore layer
      ContentUri: ./layer
      CompatibleRuntimes:
        - python2.7
        - python3.6
        - python3.7
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain
