AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Provision the AWS Lambda function of s3-monitor
###########################################################
Parameters:
###########################################################
  ENV:
    Type: String
    Default: dev
    Description: Environment name
  PROJECT:
    Type: String
    Default: no_name_project
    Description: Project name
  AWSREGION:
    Type: String
    Default: eu-west-3
    Description: AWS Region
  BUCKETSBLACKLIST:
    Type: String
    Default: no_bucket_defined
    Description: AWS S3 Bucket to exclude
  S3PREFIX:
    Type: String
    Default: no_prefix_defined
    Description: S3 prefix to monitor
  BOTOLAYER:
    Type: String
    Default: boto3
    Description: Layer name for boto3
  BOTOLAYERVERSION:
    Type: Number
    Default: 9
    Description: Layer version
  SLACKWEBHOOKURL:
    Type: String
    Default: no_slack_webhook_defined
    Description: Slack Webhook URL
###########################################################
Resources:
###########################################################
  s3monitor:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub s3-monitor-${ENV}
      Description: !Sub S3 Backup Monitor (${PROJECT})
      Handler: handlers.main
      Runtime: python3.9
      CodeUri: ./python
      MemorySize: 128
      Timeout: 300
      Layers:
        - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:${BOTOLAYER}:${BOTOLAYERVERSION}'
      Environment:
        Variables:
          S3PREFIX: !Ref S3PREFIX
          BUCKETSBLACKLIST: !Ref BUCKETSBLACKLIST
          RECIPIENTS: !Ref RECIPIENTS
          SENDER: !Ref SENDER
          AWSREGION: !Ref AWSREGION
          AWSSESREGION: !Ref AWSSESREGION
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - s3:List*
              Resource: [
                "arn:aws:s3:::*"
              ]
            - Effect: Allow
              Action:
                - ses:SendEmail
              Resource: '*'
      Events:
        Timer:
          Type: Schedule
          Properties:
            Name: s3-monitor-schedule
            Schedule: cron(0 10 * * ? *)
      Tags:
        Project: !Ref PROJECT
        Environment: !Ref ENV
        Region: !Ref AWSREGION
